# Change these first
owner: edcalderon # Your GitHub organization or username, where this repository lives
repo: uptime_wayru # The name of this repository

sites:
  - name: dapp.wayru.io
    url: https://www.dapp.wayru.io
  - name: testnet.wayru.io
    url: https://www.testnet.wayru.io
  - name: internal.wayru.co
    url: https://www.internal.wayru.co
  - name: wayru.herokuapp.com
    url: https://wayru.herokuapp.com
  - name: api.develop.wayru.co
    url: https://api.develop.wayru.co
  - name: api.internal.wayru.co
    url: https://api.internal.wayru.co
  - name: develop.network.wayru.co/graphql
    url: https://develop.network.wayru.co/graphql

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wayru.co
  # baseUrl: /your-repo-name
  logoUrl: https://res.cloudinary.com/djuadjpv0/image/upload/v1645485367/wayru_logo.89f2b60b_vkdebj.png
  name: Status Page
  introTitle: "Uptime monitor and status page for the Wayru Network projects"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
